name: needs
on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: echo "job1 done"
    job2:
        runs-on: ubuntu-latest
        needs: [job1] # job1이 실행한 후 실행되도록 needs를 통해 종속성을 걸어놓기
        steps:
            - name: echo
              run: echo "job1 done"
    job3:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: | # exit 1 을 해놓아서 job 강제 실패 됨
                  echo "job3 failed"
                  exit 1
    job4: # job3에 종속성이 걸려 있으므로 실행 안될 것
        runs-on: ubuntu-latest
        needs: [job3]
        steps:
            - name: echo
              run: echo "job4 done"
