name: string-function
on: push

jobs:
    string-function:
        runs-on: ubuntu-latest
        steps:
            - name: startswith
              if: startsWith('github actions','git')
              run: echo "git"
            - name: startswith
              if: startsWith('github actions','test')
              run: echo "test"
