name: timeout
on: push

jobs:
    timeout:
        runs-on: ubuntu-latest
        timeout-minutes: 2 # job level에서 타임아웃 설정
        steps:
            - name: loop
              run: |
                  count=0
                  while true; do
                    echo "seconds: $count"
                    count=$((count+1))
                    sleep 1
                  done
              timeout-minutes: 1 # step level에서 타임아웃 설정
            - name: echo
              run: echo hello
