name: cicd-1
on:
    pull_request:
        types: [opened, synchronized, closed] # pr 이 open 되거나, 동기화 될 때는 CI, pr이 merge되면 CD
        branches: [dev]
        paths:
            - 'react-app/**'

jobs:
    test: # pr이 open되거나 synchronize 될 때
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

    image-build: # pr이 merge될 때 - CD 단계에서 실행되는 job
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

    deploy: # image build job이 성공되면 실행되는 job - CD 단계에서 실행되는 job
        runs-on: ubuntu-latest
        needs: [image-build]
        steps:
            - name: checkout
              uses: actions/checkout@v4
