name: multiple-event-workflow
on:
    push:
    issues:
        types: [opened]
    workflow_dispatch:

jobs:
    multiple-event-job:
        runs-on: ubuntu-latest # push-job이 우분투에서 실행된다
        steps:
            - name: step1
              run: echo hello world
            - name: step2
              run: |
                  echo hello world
                  echo github action
