name: needs
on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: echo "job1 done"
    job2:
        runs-on: ubuntu-latest
        needs: [job1]
        steps:
            - name: echo
              run: echo "job1 done"
    job3:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: | # exit 1 을 해놓아서 job 강제 실패 됨
                  echo "job3 failed"
                  exit 1
    job4:
        runs-on: ubuntu-latest
        needs: [job3]
        steps:
            - name: echo
              run: echo "job4 done"
